INSERT OR IGNORE INTO tag_groups (id, name, description, sort_order)
VALUES ('grp_contact_tags', '人脉标签', '联系人关系、地域和资源属性标签', 1);

INSERT OR IGNORE INTO tags (id, group_id, name, color)
VALUES
  ('tag_contact_classmate', 'grp_contact_tags', '同学', 'blue'),
  ('tag_contact_university_classmate', 'grp_contact_tags', '大学同学', 'geekblue'),
  ('tag_contact_middle_school_classmate', 'grp_contact_tags', '初中同学', 'cyan'),
  ('tag_contact_leiyang', 'grp_contact_tags', '耒阳', 'green'),
  ('tag_contact_government', 'grp_contact_tags', '政府关系', 'volcano'),
  ('tag_contact_enterprise_customer', 'grp_contact_tags', '企业客户', 'orange'),
  ('tag_contact_oversized_industry', 'grp_contact_tags', '大件行业', 'gold'),
  ('tag_contact_ip', 'grp_contact_tags', 'IP', 'purple'),
  ('tag_contact_kuajingyi', 'grp_contact_tags', '跨境翼', 'lime'),
  ('tag_contact_colleague', 'grp_contact_tags', '同事', 'blue'),
  ('tag_contact_state_owned', 'grp_contact_tags', '国有企业', 'red'),
  ('tag_contact_hebei', 'grp_contact_tags', '河北省', 'default'),
  ('tag_contact_shanxi', 'grp_contact_tags', '山西省', 'default'),
  ('tag_contact_inner_mongolia', 'grp_contact_tags', '内蒙古', 'default'),
  ('tag_contact_liaoning', 'grp_contact_tags', '辽宁省', 'default'),
  ('tag_contact_jilin', 'grp_contact_tags', '吉林省', 'default'),
  ('tag_contact_heilongjiang', 'grp_contact_tags', '黑龙江省', 'default'),
  ('tag_contact_jiangsu', 'grp_contact_tags', '江苏省', 'default'),
  ('tag_contact_zhejiang', 'grp_contact_tags', '浙江省', 'default'),
  ('tag_contact_anhui', 'grp_contact_tags', '安徽省', 'default'),
  ('tag_contact_fujian', 'grp_contact_tags', '福建省', 'default'),
  ('tag_contact_jiangxi', 'grp_contact_tags', '江西省', 'default'),
  ('tag_contact_shandong', 'grp_contact_tags', '山东省', 'default'),
  ('tag_contact_henan', 'grp_contact_tags', '河南省', 'default'),
  ('tag_contact_hubei', 'grp_contact_tags', '湖北省', 'default'),
  ('tag_contact_hunan', 'grp_contact_tags', '湖南省', 'default'),
  ('tag_contact_guangdong', 'grp_contact_tags', '广东省', 'default'),
  ('tag_contact_hainan', 'grp_contact_tags', '海南省', 'default'),
  ('tag_contact_sichuan', 'grp_contact_tags', '四川省', 'default'),
  ('tag_contact_guizhou', 'grp_contact_tags', '贵州省', 'default'),
  ('tag_contact_yunnan', 'grp_contact_tags', '云南省', 'default'),
  ('tag_contact_shaanxi', 'grp_contact_tags', '陕西省', 'default'),
  ('tag_contact_gansu', 'grp_contact_tags', '甘肃省', 'default'),
  ('tag_contact_qinghai', 'grp_contact_tags', '青海省', 'default');
