name = "ostoa-api"
main = "src/index.ts"
compatibility_date = "2026-05-12"

[[d1_databases]]
binding = "DB"
database_name = "ostoa"
database_id = "afee03da-8eb8-49e0-977e-4fb549cff106"

[vars]
CORS_ORIGIN = "https://ostoa.org,https://www.ostoa.org,https://ostoa-web.pages.dev"
